<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2026.9.26</Version>

    <!-- URA 插件元数据 -->
    <PluginInternalName>SkillEffectPlugin</PluginInternalName>
    <PluginDisplayName>显示技能期望收益</PluginDisplayName>
    <PluginAuthor>离披&amp;ウマ娘.攻略.tools</PluginAuthor>
    <PluginDescription>未计算技能组合边际效应，仅供参考</PluginDescription>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/SkillEffectPlugin</PluginRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UmamusumeResponseAnalyzer" Version="*" PrivateAssets="all" />
  </ItemGroup>

</Project>
